### ISSUE TITLE
mocha -r global-jsdom/register module not found

### ISSUE THREAD

**Issue by kapouer** [modosc/global-jsdom#10]
Indeed, there is not file by that name.

**Comment by modosc** [comment]
thanks for the report, you are totally right.

i just updated the docs - for now you should be able to do `mocha -r global-jsdom/lib/register`. 

`jsdom-global` dumped both of these into the root directory which is why requiring `jsdom-global/register` worked. i can't  easily do that because i'm offering es6 builds as well. 

i'll leave this open and look around for a module which allows this to see what pattern they follow.

**Comment by mohanraj-r** [comment]
Guess the doc under https://github.com/modosc/global-jsdom#es2015 needs to be updated as well ? Ran into errors trying to use `import 'global-jsdom/es/register'` but `import 'global-jsdom/lib/register'` works

**Comment by modosc** [comment]
> import 'global-jsdom/lib/register'

that should be the same as 'global-jsdom/register' which is the non-es version. still looking around for a better pattern to follow on this, sorry.

**Comment by modosc** [comment]
i just pushed 7.0.0-beta.0 to npm. if you're using a version of node that supports [esm conditional exports](https://nodejs.org/api/esm.html#esm_conditional_exports) then either  `import 'global-jsdom/register'` or `require('global-jsdom/register')` should just work. @mohanraj-r @kapouer would either you be willing to check this version out to see if it solves your issues?

**Comment by modosc** [comment]
merged to master.
